import tkinter as tk

# Create the main window
root = tk.Tk()
root.title("Task Manager")

# Labels
lbl_title = tk.Label(root, text="Task Manager", font=("Arial", 16, "bold"))
lbl_title.pack(pady=10)

# Textbox for task input
txt_task = tk.Entry(root, width=30)
txt_task.pack(pady=5)

# Button to add tasks
def add_task():
    task = txt_task.get()
    # Add logic to handle task addition (e.g., store in a list or database)
    print(f"Added task: {task}")
    txt_task.delete(0, tk.END)  # Clear the textbox

btn_add = tk.Button(root, text="Add Task", command=add_task)
btn_add.pack(pady=5)

# List of tasks (you can replace this with your actual task display)
tasks = ["Task 1", "Task 2", "Task 3"]
for task in tasks:
    lbl_task = tk.Label(root, text=task)
    lbl_task.pack()

root.mainloop()
